using System.Text.Json;
using System.Text.Json.Serialization;
using QBittorrent.ApiClient.Models;

namespace QBittorrent.ApiClient
{
    [JsonSourceGenerationOptions(DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonSerializable(typeof(AddTorrentResult))]
    [JsonSerializable(typeof(ApiKey))]
    [JsonSerializable(typeof(ApplicationCookie))]
    [JsonSerializable(typeof(AutoDownloadingRule))]
    [JsonSerializable(typeof(BuildInfo))]
    [JsonSerializable(typeof(Category))]
    [JsonSerializable(typeof(DirectoryContentEntry))]
    [JsonSerializable(typeof(FileData))]
    [JsonSerializable(typeof(FetchTorrentMetadataPendingResult))]
    [JsonSerializable(typeof(GlobalTransferStatistics))]
    [JsonSerializable(typeof(Log))]
    [JsonSerializable(typeof(MainData))]
    [JsonSerializable(typeof(NetworkInterface))]
    [JsonSerializable(typeof(PeerLog))]
    [JsonSerializable(typeof(PieceState))]
    [JsonSerializable(typeof(Preferences))]
    [JsonSerializable(typeof(ProcessInfo))]
    [JsonSerializable(typeof(RssFeedItem))]
    [JsonSerializable(typeof(RssFolderItem))]
    [JsonSerializable(typeof(RssItem))]
    [JsonSerializable(typeof(SearchPlugin))]
    [JsonSerializable(typeof(SearchResults))]
    [JsonSerializable(typeof(SearchStartResult))]
    [JsonSerializable(typeof(SearchStatus))]
    [JsonSerializable(typeof(SslParameters))]
    [JsonSerializable(typeof(Torrent))]
    [JsonSerializable(typeof(TorrentCreationTaskIdentifier))]
    [JsonSerializable(typeof(TorrentCreationTaskStatus))]
    [JsonSerializable(typeof(TorrentMetadata))]
    [JsonSerializable(typeof(TorrentPeers))]
    [JsonSerializable(typeof(TorrentProperties))]
    [JsonSerializable(typeof(TorrentTracker))]
    [JsonSerializable(typeof(UpdatePreferences))]
    [JsonSerializable(typeof(WebSeed))]
    [JsonSerializable(typeof(Dictionary<string, AutoDownloadingRule>))]
    [JsonSerializable(typeof(Dictionary<string, Category>))]
    [JsonSerializable(typeof(Dictionary<string, JsonElement>))]
    [JsonSerializable(typeof(Dictionary<string, JsonElement?>))]
    [JsonSerializable(typeof(Dictionary<string, List<string>>))]
    [JsonSerializable(typeof(Dictionary<string, long>))]
    [JsonSerializable(typeof(Dictionary<string, RssItem>))]
    [JsonSerializable(typeof(Dictionary<string, TorrentMetadata>))]
    [JsonSerializable(typeof(List<ApplicationCookie>))]
    [JsonSerializable(typeof(List<DirectoryContentEntry>))]
    [JsonSerializable(typeof(List<FileData>))]
    [JsonSerializable(typeof(List<int>))]
    [JsonSerializable(typeof(List<Log>))]
    [JsonSerializable(typeof(List<NetworkInterface>))]
    [JsonSerializable(typeof(List<PeerLog>))]
    [JsonSerializable(typeof(List<PieceState>))]
    [JsonSerializable(typeof(List<RssArticle>))]
    [JsonSerializable(typeof(List<SearchPlugin>))]
    [JsonSerializable(typeof(List<SearchStatus>))]
    [JsonSerializable(typeof(List<string>))]
    [JsonSerializable(typeof(List<Torrent>))]
    [JsonSerializable(typeof(List<TorrentCreationTaskStatus>))]
    [JsonSerializable(typeof(List<TorrentMetadata>))]
    [JsonSerializable(typeof(List<TorrentTracker>))]
    [JsonSerializable(typeof(List<WebSeed>))]
    [JsonSerializable(typeof(string[]))]
    internal sealed partial class QBittorrentJsonSerializerContext : JsonSerializerContext
    {
    }
}
