<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>QBittorrent.ApiClient</AssemblyName>
    <RootNamespace>QBittorrent.ApiClient</RootNamespace>
    <PackageId>QBittorrent.ApiClient</PackageId>
    <Title>QBittorrent.ApiClient</Title>
    <Description>.NET client library for the qBittorrent Web API.</Description>
    <Authors>Lantean Code</Authors>
    <Company>Lantean Code</Company>
    <PackageTags>qbittorrent;webapi;api-client;dotnet</PackageTags>
    <RepositoryUrl>https://github.com/lantean-code/QBittorrent.ApiClient</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/lantean-code/QBittorrent.ApiClient</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IsPackable>true</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="QBittorrent.ApiClient.Test" />
  </ItemGroup>

  <ItemGroup Condition="Exists('..\..\.git')">
    <PackageReference Include="GitVersion.MsBuild" Version="6.7.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.201">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\..\LICENSE" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
